/*
Sonarr

Sonarr API docs

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// QueueResource struct for QueueResource
type QueueResource struct {
	Id *int32 `json:"id,omitempty"`
	SeriesId NullableInt32 `json:"seriesId,omitempty"`
	EpisodeId NullableInt32 `json:"episodeId,omitempty"`
	Series *SeriesResource `json:"series,omitempty"`
	Episode *EpisodeResource `json:"episode,omitempty"`
	Language *Language `json:"language,omitempty"`
	Quality *QualityModel `json:"quality,omitempty"`
	CustomFormats []CustomFormatResource `json:"customFormats,omitempty"`
	Size *float64 `json:"size,omitempty"`
	Title NullableString `json:"title,omitempty"`
	Sizeleft *float64 `json:"sizeleft,omitempty"`
	Timeleft *TimeSpan `json:"timeleft,omitempty"`
	EstimatedCompletionTime NullableTime `json:"estimatedCompletionTime,omitempty"`
	Status NullableString `json:"status,omitempty"`
	TrackedDownloadStatus *TrackedDownloadStatus `json:"trackedDownloadStatus,omitempty"`
	TrackedDownloadState *TrackedDownloadState `json:"trackedDownloadState,omitempty"`
	StatusMessages []TrackedDownloadStatusMessage `json:"statusMessages,omitempty"`
	ErrorMessage NullableString `json:"errorMessage,omitempty"`
	DownloadId NullableString `json:"downloadId,omitempty"`
	Protocol *DownloadProtocol `json:"protocol,omitempty"`
	DownloadClient NullableString `json:"downloadClient,omitempty"`
	Indexer NullableString `json:"indexer,omitempty"`
	OutputPath NullableString `json:"outputPath,omitempty"`
}

// NewQueueResource instantiates a new QueueResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueueResource() *QueueResource {
	this := QueueResource{}
	return &this
}

// NewQueueResourceWithDefaults instantiates a new QueueResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueueResourceWithDefaults() *QueueResource {
	this := QueueResource{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *QueueResource) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueResource) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *QueueResource) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *QueueResource) SetId(v int32) {
	o.Id = &v
}

// GetSeriesId returns the SeriesId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueueResource) GetSeriesId() int32 {
	if o == nil || o.SeriesId.Get() == nil {
		var ret int32
		return ret
	}
	return *o.SeriesId.Get()
}

// GetSeriesIdOk returns a tuple with the SeriesId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueueResource) GetSeriesIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SeriesId.Get(), o.SeriesId.IsSet()
}

// HasSeriesId returns a boolean if a field has been set.
func (o *QueueResource) HasSeriesId() bool {
	if o != nil && o.SeriesId.IsSet() {
		return true
	}

	return false
}

// SetSeriesId gets a reference to the given NullableInt32 and assigns it to the SeriesId field.
func (o *QueueResource) SetSeriesId(v int32) {
	o.SeriesId.Set(&v)
}
// SetSeriesIdNil sets the value for SeriesId to be an explicit nil
func (o *QueueResource) SetSeriesIdNil() {
	o.SeriesId.Set(nil)
}

// UnsetSeriesId ensures that no value is present for SeriesId, not even an explicit nil
func (o *QueueResource) UnsetSeriesId() {
	o.SeriesId.Unset()
}

// GetEpisodeId returns the EpisodeId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueueResource) GetEpisodeId() int32 {
	if o == nil || o.EpisodeId.Get() == nil {
		var ret int32
		return ret
	}
	return *o.EpisodeId.Get()
}

// GetEpisodeIdOk returns a tuple with the EpisodeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueueResource) GetEpisodeIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.EpisodeId.Get(), o.EpisodeId.IsSet()
}

// HasEpisodeId returns a boolean if a field has been set.
func (o *QueueResource) HasEpisodeId() bool {
	if o != nil && o.EpisodeId.IsSet() {
		return true
	}

	return false
}

// SetEpisodeId gets a reference to the given NullableInt32 and assigns it to the EpisodeId field.
func (o *QueueResource) SetEpisodeId(v int32) {
	o.EpisodeId.Set(&v)
}
// SetEpisodeIdNil sets the value for EpisodeId to be an explicit nil
func (o *QueueResource) SetEpisodeIdNil() {
	o.EpisodeId.Set(nil)
}

// UnsetEpisodeId ensures that no value is present for EpisodeId, not even an explicit nil
func (o *QueueResource) UnsetEpisodeId() {
	o.EpisodeId.Unset()
}

// GetSeries returns the Series field value if set, zero value otherwise.
func (o *QueueResource) GetSeries() SeriesResource {
	if o == nil || o.Series == nil {
		var ret SeriesResource
		return ret
	}
	return *o.Series
}

// GetSeriesOk returns a tuple with the Series field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueResource) GetSeriesOk() (*SeriesResource, bool) {
	if o == nil || o.Series == nil {
		return nil, false
	}
	return o.Series, true
}

// HasSeries returns a boolean if a field has been set.
func (o *QueueResource) HasSeries() bool {
	if o != nil && o.Series != nil {
		return true
	}

	return false
}

// SetSeries gets a reference to the given SeriesResource and assigns it to the Series field.
func (o *QueueResource) SetSeries(v SeriesResource) {
	o.Series = &v
}

// GetEpisode returns the Episode field value if set, zero value otherwise.
func (o *QueueResource) GetEpisode() EpisodeResource {
	if o == nil || o.Episode == nil {
		var ret EpisodeResource
		return ret
	}
	return *o.Episode
}

// GetEpisodeOk returns a tuple with the Episode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueResource) GetEpisodeOk() (*EpisodeResource, bool) {
	if o == nil || o.Episode == nil {
		return nil, false
	}
	return o.Episode, true
}

// HasEpisode returns a boolean if a field has been set.
func (o *QueueResource) HasEpisode() bool {
	if o != nil && o.Episode != nil {
		return true
	}

	return false
}

// SetEpisode gets a reference to the given EpisodeResource and assigns it to the Episode field.
func (o *QueueResource) SetEpisode(v EpisodeResource) {
	o.Episode = &v
}

// GetLanguage returns the Language field value if set, zero value otherwise.
func (o *QueueResource) GetLanguage() Language {
	if o == nil || o.Language == nil {
		var ret Language
		return ret
	}
	return *o.Language
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueResource) GetLanguageOk() (*Language, bool) {
	if o == nil || o.Language == nil {
		return nil, false
	}
	return o.Language, true
}

// HasLanguage returns a boolean if a field has been set.
func (o *QueueResource) HasLanguage() bool {
	if o != nil && o.Language != nil {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given Language and assigns it to the Language field.
func (o *QueueResource) SetLanguage(v Language) {
	o.Language = &v
}

// GetQuality returns the Quality field value if set, zero value otherwise.
func (o *QueueResource) GetQuality() QualityModel {
	if o == nil || o.Quality == nil {
		var ret QualityModel
		return ret
	}
	return *o.Quality
}

// GetQualityOk returns a tuple with the Quality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueResource) GetQualityOk() (*QualityModel, bool) {
	if o == nil || o.Quality == nil {
		return nil, false
	}
	return o.Quality, true
}

// HasQuality returns a boolean if a field has been set.
func (o *QueueResource) HasQuality() bool {
	if o != nil && o.Quality != nil {
		return true
	}

	return false
}

// SetQuality gets a reference to the given QualityModel and assigns it to the Quality field.
func (o *QueueResource) SetQuality(v QualityModel) {
	o.Quality = &v
}

// GetCustomFormats returns the CustomFormats field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueueResource) GetCustomFormats() []CustomFormatResource {
	if o == nil {
		var ret []CustomFormatResource
		return ret
	}
	return o.CustomFormats
}

// GetCustomFormatsOk returns a tuple with the CustomFormats field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueueResource) GetCustomFormatsOk() ([]CustomFormatResource, bool) {
	if o == nil || o.CustomFormats == nil {
		return nil, false
	}
	return o.CustomFormats, true
}

// HasCustomFormats returns a boolean if a field has been set.
func (o *QueueResource) HasCustomFormats() bool {
	if o != nil && o.CustomFormats != nil {
		return true
	}

	return false
}

// SetCustomFormats gets a reference to the given []CustomFormatResource and assigns it to the CustomFormats field.
func (o *QueueResource) SetCustomFormats(v []CustomFormatResource) {
	o.CustomFormats = v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *QueueResource) GetSize() float64 {
	if o == nil || o.Size == nil {
		var ret float64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueResource) GetSizeOk() (*float64, bool) {
	if o == nil || o.Size == nil {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *QueueResource) HasSize() bool {
	if o != nil && o.Size != nil {
		return true
	}

	return false
}

// SetSize gets a reference to the given float64 and assigns it to the Size field.
func (o *QueueResource) SetSize(v float64) {
	o.Size = &v
}

// GetTitle returns the Title field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueueResource) GetTitle() string {
	if o == nil || o.Title.Get() == nil {
		var ret string
		return ret
	}
	return *o.Title.Get()
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueueResource) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Title.Get(), o.Title.IsSet()
}

// HasTitle returns a boolean if a field has been set.
func (o *QueueResource) HasTitle() bool {
	if o != nil && o.Title.IsSet() {
		return true
	}

	return false
}

// SetTitle gets a reference to the given NullableString and assigns it to the Title field.
func (o *QueueResource) SetTitle(v string) {
	o.Title.Set(&v)
}
// SetTitleNil sets the value for Title to be an explicit nil
func (o *QueueResource) SetTitleNil() {
	o.Title.Set(nil)
}

// UnsetTitle ensures that no value is present for Title, not even an explicit nil
func (o *QueueResource) UnsetTitle() {
	o.Title.Unset()
}

// GetSizeleft returns the Sizeleft field value if set, zero value otherwise.
func (o *QueueResource) GetSizeleft() float64 {
	if o == nil || o.Sizeleft == nil {
		var ret float64
		return ret
	}
	return *o.Sizeleft
}

// GetSizeleftOk returns a tuple with the Sizeleft field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueResource) GetSizeleftOk() (*float64, bool) {
	if o == nil || o.Sizeleft == nil {
		return nil, false
	}
	return o.Sizeleft, true
}

// HasSizeleft returns a boolean if a field has been set.
func (o *QueueResource) HasSizeleft() bool {
	if o != nil && o.Sizeleft != nil {
		return true
	}

	return false
}

// SetSizeleft gets a reference to the given float64 and assigns it to the Sizeleft field.
func (o *QueueResource) SetSizeleft(v float64) {
	o.Sizeleft = &v
}

// GetTimeleft returns the Timeleft field value if set, zero value otherwise.
func (o *QueueResource) GetTimeleft() TimeSpan {
	if o == nil || o.Timeleft == nil {
		var ret TimeSpan
		return ret
	}
	return *o.Timeleft
}

// GetTimeleftOk returns a tuple with the Timeleft field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueResource) GetTimeleftOk() (*TimeSpan, bool) {
	if o == nil || o.Timeleft == nil {
		return nil, false
	}
	return o.Timeleft, true
}

// HasTimeleft returns a boolean if a field has been set.
func (o *QueueResource) HasTimeleft() bool {
	if o != nil && o.Timeleft != nil {
		return true
	}

	return false
}

// SetTimeleft gets a reference to the given TimeSpan and assigns it to the Timeleft field.
func (o *QueueResource) SetTimeleft(v TimeSpan) {
	o.Timeleft = &v
}

// GetEstimatedCompletionTime returns the EstimatedCompletionTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueueResource) GetEstimatedCompletionTime() time.Time {
	if o == nil || o.EstimatedCompletionTime.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.EstimatedCompletionTime.Get()
}

// GetEstimatedCompletionTimeOk returns a tuple with the EstimatedCompletionTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueueResource) GetEstimatedCompletionTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EstimatedCompletionTime.Get(), o.EstimatedCompletionTime.IsSet()
}

// HasEstimatedCompletionTime returns a boolean if a field has been set.
func (o *QueueResource) HasEstimatedCompletionTime() bool {
	if o != nil && o.EstimatedCompletionTime.IsSet() {
		return true
	}

	return false
}

// SetEstimatedCompletionTime gets a reference to the given NullableTime and assigns it to the EstimatedCompletionTime field.
func (o *QueueResource) SetEstimatedCompletionTime(v time.Time) {
	o.EstimatedCompletionTime.Set(&v)
}
// SetEstimatedCompletionTimeNil sets the value for EstimatedCompletionTime to be an explicit nil
func (o *QueueResource) SetEstimatedCompletionTimeNil() {
	o.EstimatedCompletionTime.Set(nil)
}

// UnsetEstimatedCompletionTime ensures that no value is present for EstimatedCompletionTime, not even an explicit nil
func (o *QueueResource) UnsetEstimatedCompletionTime() {
	o.EstimatedCompletionTime.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueueResource) GetStatus() string {
	if o == nil || o.Status.Get() == nil {
		var ret string
		return ret
	}
	return *o.Status.Get()
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueueResource) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Status.Get(), o.Status.IsSet()
}

// HasStatus returns a boolean if a field has been set.
func (o *QueueResource) HasStatus() bool {
	if o != nil && o.Status.IsSet() {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NullableString and assigns it to the Status field.
func (o *QueueResource) SetStatus(v string) {
	o.Status.Set(&v)
}
// SetStatusNil sets the value for Status to be an explicit nil
func (o *QueueResource) SetStatusNil() {
	o.Status.Set(nil)
}

// UnsetStatus ensures that no value is present for Status, not even an explicit nil
func (o *QueueResource) UnsetStatus() {
	o.Status.Unset()
}

// GetTrackedDownloadStatus returns the TrackedDownloadStatus field value if set, zero value otherwise.
func (o *QueueResource) GetTrackedDownloadStatus() TrackedDownloadStatus {
	if o == nil || o.TrackedDownloadStatus == nil {
		var ret TrackedDownloadStatus
		return ret
	}
	return *o.TrackedDownloadStatus
}

// GetTrackedDownloadStatusOk returns a tuple with the TrackedDownloadStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueResource) GetTrackedDownloadStatusOk() (*TrackedDownloadStatus, bool) {
	if o == nil || o.TrackedDownloadStatus == nil {
		return nil, false
	}
	return o.TrackedDownloadStatus, true
}

// HasTrackedDownloadStatus returns a boolean if a field has been set.
func (o *QueueResource) HasTrackedDownloadStatus() bool {
	if o != nil && o.TrackedDownloadStatus != nil {
		return true
	}

	return false
}

// SetTrackedDownloadStatus gets a reference to the given TrackedDownloadStatus and assigns it to the TrackedDownloadStatus field.
func (o *QueueResource) SetTrackedDownloadStatus(v TrackedDownloadStatus) {
	o.TrackedDownloadStatus = &v
}

// GetTrackedDownloadState returns the TrackedDownloadState field value if set, zero value otherwise.
func (o *QueueResource) GetTrackedDownloadState() TrackedDownloadState {
	if o == nil || o.TrackedDownloadState == nil {
		var ret TrackedDownloadState
		return ret
	}
	return *o.TrackedDownloadState
}

// GetTrackedDownloadStateOk returns a tuple with the TrackedDownloadState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueResource) GetTrackedDownloadStateOk() (*TrackedDownloadState, bool) {
	if o == nil || o.TrackedDownloadState == nil {
		return nil, false
	}
	return o.TrackedDownloadState, true
}

// HasTrackedDownloadState returns a boolean if a field has been set.
func (o *QueueResource) HasTrackedDownloadState() bool {
	if o != nil && o.TrackedDownloadState != nil {
		return true
	}

	return false
}

// SetTrackedDownloadState gets a reference to the given TrackedDownloadState and assigns it to the TrackedDownloadState field.
func (o *QueueResource) SetTrackedDownloadState(v TrackedDownloadState) {
	o.TrackedDownloadState = &v
}

// GetStatusMessages returns the StatusMessages field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueueResource) GetStatusMessages() []TrackedDownloadStatusMessage {
	if o == nil {
		var ret []TrackedDownloadStatusMessage
		return ret
	}
	return o.StatusMessages
}

// GetStatusMessagesOk returns a tuple with the StatusMessages field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueueResource) GetStatusMessagesOk() ([]TrackedDownloadStatusMessage, bool) {
	if o == nil || o.StatusMessages == nil {
		return nil, false
	}
	return o.StatusMessages, true
}

// HasStatusMessages returns a boolean if a field has been set.
func (o *QueueResource) HasStatusMessages() bool {
	if o != nil && o.StatusMessages != nil {
		return true
	}

	return false
}

// SetStatusMessages gets a reference to the given []TrackedDownloadStatusMessage and assigns it to the StatusMessages field.
func (o *QueueResource) SetStatusMessages(v []TrackedDownloadStatusMessage) {
	o.StatusMessages = v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueueResource) GetErrorMessage() string {
	if o == nil || o.ErrorMessage.Get() == nil {
		var ret string
		return ret
	}
	return *o.ErrorMessage.Get()
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueueResource) GetErrorMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorMessage.Get(), o.ErrorMessage.IsSet()
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *QueueResource) HasErrorMessage() bool {
	if o != nil && o.ErrorMessage.IsSet() {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given NullableString and assigns it to the ErrorMessage field.
func (o *QueueResource) SetErrorMessage(v string) {
	o.ErrorMessage.Set(&v)
}
// SetErrorMessageNil sets the value for ErrorMessage to be an explicit nil
func (o *QueueResource) SetErrorMessageNil() {
	o.ErrorMessage.Set(nil)
}

// UnsetErrorMessage ensures that no value is present for ErrorMessage, not even an explicit nil
func (o *QueueResource) UnsetErrorMessage() {
	o.ErrorMessage.Unset()
}

// GetDownloadId returns the DownloadId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueueResource) GetDownloadId() string {
	if o == nil || o.DownloadId.Get() == nil {
		var ret string
		return ret
	}
	return *o.DownloadId.Get()
}

// GetDownloadIdOk returns a tuple with the DownloadId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueueResource) GetDownloadIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DownloadId.Get(), o.DownloadId.IsSet()
}

// HasDownloadId returns a boolean if a field has been set.
func (o *QueueResource) HasDownloadId() bool {
	if o != nil && o.DownloadId.IsSet() {
		return true
	}

	return false
}

// SetDownloadId gets a reference to the given NullableString and assigns it to the DownloadId field.
func (o *QueueResource) SetDownloadId(v string) {
	o.DownloadId.Set(&v)
}
// SetDownloadIdNil sets the value for DownloadId to be an explicit nil
func (o *QueueResource) SetDownloadIdNil() {
	o.DownloadId.Set(nil)
}

// UnsetDownloadId ensures that no value is present for DownloadId, not even an explicit nil
func (o *QueueResource) UnsetDownloadId() {
	o.DownloadId.Unset()
}

// GetProtocol returns the Protocol field value if set, zero value otherwise.
func (o *QueueResource) GetProtocol() DownloadProtocol {
	if o == nil || o.Protocol == nil {
		var ret DownloadProtocol
		return ret
	}
	return *o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueResource) GetProtocolOk() (*DownloadProtocol, bool) {
	if o == nil || o.Protocol == nil {
		return nil, false
	}
	return o.Protocol, true
}

// HasProtocol returns a boolean if a field has been set.
func (o *QueueResource) HasProtocol() bool {
	if o != nil && o.Protocol != nil {
		return true
	}

	return false
}

// SetProtocol gets a reference to the given DownloadProtocol and assigns it to the Protocol field.
func (o *QueueResource) SetProtocol(v DownloadProtocol) {
	o.Protocol = &v
}

// GetDownloadClient returns the DownloadClient field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueueResource) GetDownloadClient() string {
	if o == nil || o.DownloadClient.Get() == nil {
		var ret string
		return ret
	}
	return *o.DownloadClient.Get()
}

// GetDownloadClientOk returns a tuple with the DownloadClient field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueueResource) GetDownloadClientOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DownloadClient.Get(), o.DownloadClient.IsSet()
}

// HasDownloadClient returns a boolean if a field has been set.
func (o *QueueResource) HasDownloadClient() bool {
	if o != nil && o.DownloadClient.IsSet() {
		return true
	}

	return false
}

// SetDownloadClient gets a reference to the given NullableString and assigns it to the DownloadClient field.
func (o *QueueResource) SetDownloadClient(v string) {
	o.DownloadClient.Set(&v)
}
// SetDownloadClientNil sets the value for DownloadClient to be an explicit nil
func (o *QueueResource) SetDownloadClientNil() {
	o.DownloadClient.Set(nil)
}

// UnsetDownloadClient ensures that no value is present for DownloadClient, not even an explicit nil
func (o *QueueResource) UnsetDownloadClient() {
	o.DownloadClient.Unset()
}

// GetIndexer returns the Indexer field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueueResource) GetIndexer() string {
	if o == nil || o.Indexer.Get() == nil {
		var ret string
		return ret
	}
	return *o.Indexer.Get()
}

// GetIndexerOk returns a tuple with the Indexer field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueueResource) GetIndexerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Indexer.Get(), o.Indexer.IsSet()
}

// HasIndexer returns a boolean if a field has been set.
func (o *QueueResource) HasIndexer() bool {
	if o != nil && o.Indexer.IsSet() {
		return true
	}

	return false
}

// SetIndexer gets a reference to the given NullableString and assigns it to the Indexer field.
func (o *QueueResource) SetIndexer(v string) {
	o.Indexer.Set(&v)
}
// SetIndexerNil sets the value for Indexer to be an explicit nil
func (o *QueueResource) SetIndexerNil() {
	o.Indexer.Set(nil)
}

// UnsetIndexer ensures that no value is present for Indexer, not even an explicit nil
func (o *QueueResource) UnsetIndexer() {
	o.Indexer.Unset()
}

// GetOutputPath returns the OutputPath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueueResource) GetOutputPath() string {
	if o == nil || o.OutputPath.Get() == nil {
		var ret string
		return ret
	}
	return *o.OutputPath.Get()
}

// GetOutputPathOk returns a tuple with the OutputPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueueResource) GetOutputPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OutputPath.Get(), o.OutputPath.IsSet()
}

// HasOutputPath returns a boolean if a field has been set.
func (o *QueueResource) HasOutputPath() bool {
	if o != nil && o.OutputPath.IsSet() {
		return true
	}

	return false
}

// SetOutputPath gets a reference to the given NullableString and assigns it to the OutputPath field.
func (o *QueueResource) SetOutputPath(v string) {
	o.OutputPath.Set(&v)
}
// SetOutputPathNil sets the value for OutputPath to be an explicit nil
func (o *QueueResource) SetOutputPathNil() {
	o.OutputPath.Set(nil)
}

// UnsetOutputPath ensures that no value is present for OutputPath, not even an explicit nil
func (o *QueueResource) UnsetOutputPath() {
	o.OutputPath.Unset()
}

func (o QueueResource) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.SeriesId.IsSet() {
		toSerialize["seriesId"] = o.SeriesId.Get()
	}
	if o.EpisodeId.IsSet() {
		toSerialize["episodeId"] = o.EpisodeId.Get()
	}
	if o.Series != nil {
		toSerialize["series"] = o.Series
	}
	if o.Episode != nil {
		toSerialize["episode"] = o.Episode
	}
	if o.Language != nil {
		toSerialize["language"] = o.Language
	}
	if o.Quality != nil {
		toSerialize["quality"] = o.Quality
	}
	if o.CustomFormats != nil {
		toSerialize["customFormats"] = o.CustomFormats
	}
	if o.Size != nil {
		toSerialize["size"] = o.Size
	}
	if o.Title.IsSet() {
		toSerialize["title"] = o.Title.Get()
	}
	if o.Sizeleft != nil {
		toSerialize["sizeleft"] = o.Sizeleft
	}
	if o.Timeleft != nil {
		toSerialize["timeleft"] = o.Timeleft
	}
	if o.EstimatedCompletionTime.IsSet() {
		toSerialize["estimatedCompletionTime"] = o.EstimatedCompletionTime.Get()
	}
	if o.Status.IsSet() {
		toSerialize["status"] = o.Status.Get()
	}
	if o.TrackedDownloadStatus != nil {
		toSerialize["trackedDownloadStatus"] = o.TrackedDownloadStatus
	}
	if o.TrackedDownloadState != nil {
		toSerialize["trackedDownloadState"] = o.TrackedDownloadState
	}
	if o.StatusMessages != nil {
		toSerialize["statusMessages"] = o.StatusMessages
	}
	if o.ErrorMessage.IsSet() {
		toSerialize["errorMessage"] = o.ErrorMessage.Get()
	}
	if o.DownloadId.IsSet() {
		toSerialize["downloadId"] = o.DownloadId.Get()
	}
	if o.Protocol != nil {
		toSerialize["protocol"] = o.Protocol
	}
	if o.DownloadClient.IsSet() {
		toSerialize["downloadClient"] = o.DownloadClient.Get()
	}
	if o.Indexer.IsSet() {
		toSerialize["indexer"] = o.Indexer.Get()
	}
	if o.OutputPath.IsSet() {
		toSerialize["outputPath"] = o.OutputPath.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableQueueResource struct {
	value *QueueResource
	isSet bool
}

func (v NullableQueueResource) Get() *QueueResource {
	return v.value
}

func (v *NullableQueueResource) Set(val *QueueResource) {
	v.value = val
	v.isSet = true
}

func (v NullableQueueResource) IsSet() bool {
	return v.isSet
}

func (v *NullableQueueResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueueResource(val *QueueResource) *NullableQueueResource {
	return &NullableQueueResource{value: val, isSet: true}
}

func (v NullableQueueResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueueResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


